### ISSUE TITLE
运行resnet50.py报错

### ISSUE THREAD

**Issue by 97shimmer** [bubbliiiing/classic-convolution-network#1]
错误如下：
Traceback (most recent call last):
  File "D:/pythonwork/pycharm_work/classic-convolution-network-master/resnet50.py", line 5, in <module>
    from keras import layers
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\keras\__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 48, in <module>
    from tensorflow.python import keras
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\models.py", line 23, in <module>
    from tensorflow.python.keras import backend as K
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\backend.py", line 38, in <module>
    from tensorflow.python.distribute import distribute_coordinator as dc
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\distribute\distribute_coordinator.py", line 33, in <module>
    from tensorflow.python.training import monitored_session
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 45, in <module>
    from tensorflow.python.training.tracking import graph_view
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 27, in <module>
    from tensorflow.python.training import optimizer as optimizer_v1
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\optimizer.py", line 36, in <module>
    from tensorflow.python.ops import gradients
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gradients.py", line 24, in <module>
    from tensorflow.python.eager.forwardprop import ForwardAccumulator
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\forwardprop.py", line 36, in <module>
    from tensorflow.python.ops.parallel_for import control_flow_ops
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\parallel_for\__init__.py", line 22, in <module>
    from tensorflow.python.ops.parallel_for.control_flow_ops import for_loop
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\parallel_for\control_flow_ops.py", line 36, in <module>
    from tensorflow.python.ops.parallel_for.pfor import PFor
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\parallel_for\pfor.py", line 30, in <module>
    from tensorflow.compiler.tf2xla.python import xla
  File "D:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\compiler\tf2xla\python\xla.py", line 106, in <module>
    bessel_i0e = _unary_op(math_ops.bessel_i0e)
AttributeError: module 'tensorflow.python.ops.math_ops' has no attribute 'bessel_i0e'

请帮我看看，谢啦

**Comment by bubbliiiing** [comment]
你这是环境配置问题吧应该

**Comment by ZZHHogan** [comment]
估计是版本问题

**Comment by bubbliiiing** [comment]
嗯
